// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuCombiAppBackend;

namespace TuCombiAppBackend.Migrations
{
    [DbContext(typeof(CombiContext))]
    [Migration("20191026175800_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TuCombiAppBackend.Models.Combi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("pasajeros");

                    b.Property<string>("placa");

                    b.HasKey("id");

                    b.ToTable("Combis");
                });
#pragma warning restore 612, 618
        }
    }
}
